name: SimpleBotCI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create .env file from secrets
        run: echo "{\"token\":\"${{ secrets.TOKEN }}\"}" > secrets.json
      - name: Install requirements
        run: pip install --no-cache-dir -r requirements.txt
      - name: Build Perlin.c
        run: |
          sudo apt-get install build-essential cmake 
          export CC=gcc
          cmake .
          make
      - name: CI the bot for 5 min
        timeout-minutes: 5
        run: python bot.py
      - name: Status Report
        if: always()
        run: echo "Ok"
